 name: gitartwork
 on: 
   push:
   schedule:
     - cron: '* */24 * * *'
 jobs:
   build:
     name: Make gitartwork SVG
     runs-on: bayo
     steps:
       - uses: actions/checkout@v3
       - uses: Bayzng/gitartwork@v1
         with:
            # Use this username's contribution graph  
            user_name: Bayzng
            # Text on contribution graph 
            text: BAYZ
       - uses: Bayzng/simple-push-action@v1
